spring:
  profiles:
    active: local # 디폴트 환경
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: pebblepark@$#
  social:
    kakao:
      client_id: 1046b5d73c7d470e631405468a45787e
      redirect: /social/login/kakao
      url:
        login: https://kauth.kakao.com/oauth/authorize
        token: http://kauth.kakao.com/oauth/token
        profile: https://kapi.kakao.com/v2/user/me